### PR TITLE
Updates range

### PR DESCRIPTION
**Pull request by nexor**
Relates to https://github.com/nexor/telega/pull/11

### CODE REVIEW

**Comment by denizzzka** [comment]
Time is come!

**Comment by nexor** [comment]
@denizzzka why it is not suitable? What can't ve done using this approach?

I suppose it can be used in the usual way:
```
        uint maxUpdateId = loadMaxUpdateId(); // load max update id from storage
        auto api = new BotApi(botToken);
        auto updatesRange = new UpdatesRange(api, maxUpdateId);

        foreach (ref Update u; updatesRange) {
            if (u.isMessageType && u.message.chat.id == 123) {
              api.sendMessage(123, m.text); // answer ot chat message
            } else {
                // do something else with update
            }

            saveMaxUpdateId(updatesRange.maxUpdateId); // save current processed update id
        }
```

**Comment by denizzzka** [comment]
Ah, just forgot about `saveMaxUpdateId`

**Comment by nexor** [comment]
Note that `loadMaxUpdateId()` and `saveMaxUpdateId(updatesRange.maxUpdateId)` is not part of the library, you have to implement them by yourself.

**Comment by nexor** [comment]
It's OK for now. Any further issues are welcome.

**Pull request merged**
