### PR TITLE
offset is long in TG API terms

### PR DESCRIPTION
**Pull request by denizzzka**
Hi! I saw that there was an update and also decided to add something

### CODE REVIEW

**Comment by nexor** [comment]
@denizzzka hey, could you please paste the link to the documentation? I found no information that offset can be larger than int as per official docs https://core.telegram.org/bots/api#getupdates 

I also looked at the similar library in c# https://github.com/TelegramBots/Telegram.Bot/blob/master/src/Telegram.Bot/Requests/Getting%20Updates/GetUpdatesRequest.cs#L34
and seems that int is enough size for the offset.

**Comment by denizzzka** [comment]
`Integer` is long, it seems

because initially they used JSON, which treated integer as long

**Comment by cyrusmsk** [comment]
Seems so:
https://github.com/omarmiatello/telegram-api-generator/blob/43bae5f2792bbd242bc5ced56211ab07e48300e1/src/main/kotlin/GeneratorKotlin.kt#L257
```kotlin
TelegramType.Integer -> "Long"
```

**Comment by nexor** [comment]
I suggest to close this PR since most of libraries use 4-bytes offset size, here are some examples:

https://github.com/reo7sp/tgbot-cpp/blob/master/src/Api.cpp#L12C42-L12C54

https://github.com/teloxide/teloxide/blob/bd98ba7e613e0fd7ec4fd1c210fc5edbb048f975/crates/teloxide/src/update_listeners/polling.rs#L301


Also according to the documentation:
```
It is safe to use 32-bit signed integers for storing all Integer fields unless otherwise noted.
```

**Pull request closed without merging**
